#pragma once

namespace Config
{
  enum class Result
  {
    OK = 0,
    UNKNOWN_TYPE,
    MISSING_TYPE_FOR_CONFIG,
    MISSING_CONFIG_FOR_TYPE,
    GPIO_MISSING_LINES,
    GPIO_MISSING_DIRECTION,
    MISSING_SETTING_PATH,
    AUDIO_MISSING_API,
    AUDIO_MISSING_CHANNELS,
    AUDIO_MISSING_SAMPLE_RATE,
    AUDIO_MISSING_SEARCH_EXPRESSION,
    AUDIO_MISSING_FORMAT,
    AUDIO_MISSING_IS_INPUT,
    AUDIO_MISSING_IS_IQ,
    BAND_SELECTOR_MISSING_DEFAULT_OUT,
    BAND_SELECTOR_MISSING_BANDS,
    BAND_MISSING_FROM_FREQUENCY,
    BAND_MISSING_TO_FREQUENCY,
    BAND_MISSING_OUT_VALUE,
    MISSING_IQ_SOURCE,
    MISSING_AUDIO_OUTPUT
  };
}