#pragma once

#ifdef USE_ETL
#include "etl/optional.h"
#include "etl/variant.h"
#include "etl/memory.h"
#include "etl/vector.h"
#include "etl/algorithm.h"
#include "etl/functional.h"
using etl::variant;
using etl::holds_alternative;
using etl::get;
using etl::visit;
using etl::unique_ptr;
using etl::optional;
using etl::nullopt;
using etl::move;
using etl::monostate;
using etl::decay_t;
using etl::is_same_v;
using etl::get_if;
using etl::reference_wrapper;
using etl::is_arithmetic_v;
using etl::find_if;
using etl::distance;
using etl::any_of;
using etl::ref;
using etl::make_pair;
using etl::function;

#else
#include <variant>
#include <memory>
#include <optional>
#include <vector>
#include <algorithm>
#include <functional>
using std::variant;
using std::holds_alternative;
using std::get;
using std::visit;
using std::unique_ptr;
using std::optional;
using std::nullopt;
using std::move;
using std::monostate;
using std::decay_t;
using std::is_same_v;
using std::get_if;
using std::reference_wrapper;
using std::is_arithmetic_v;
using std::find_if;
using std::distance;
using std::any_of;
using std::ref;
using std::make_pair;
using std::function;
#endif