#pragma once

enum class ResultCode
{
  OK = 0,
  ERR_CONFIG_CONTROL_SINK,
  ERR_CONFIG_CONTROL_SOURCE,
  ERR_CONTROL_SINK,
  ERR_CONTROL_SOURCE,
  ERR_NO_CONTROL_SOURCES_DEFINED,
  ERR_DIGITAL_OUTPUT_LINES,
  ERR_NO_GPIO_PRESENT,
  ERR_NOTIFY_SETTINGS_NOT_IMPLEMENTED,
  ERR_DIGITAL_INPUT_UNKNOWN_TYPE,
  ERR_UNKNOWN_SETTING_PATH,
  ERR_UNKNOWN_DIGITAL_INPUT
};